- hosts: webserver
  
  tasks: 
    - name: install git
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: yes

    - name: remove git
      ansible.builtin.apt:
        name: git
        state: absent
        update_cache: yes
